# Generated by Django 6.0 on 2026-03-03 09:38

import care.utils.time_util
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emr', '0075_chargeitem_discount_configuration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoAssignmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('triggered_at', models.DateTimeField(default=care.utils.time_util.care_now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='care_quick__status_9c5cd8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('assigned_staff__isnull', True), ('completed_at__isnull', True), ('failure_reason__isnull', True), ('status', 'PENDING')), models.Q(('assigned_staff__isnull', True), ('completed_at__isnull', False), ('failure_reason__isnull', False), ('status', 'FAILED')), models.Q(('assigned_staff__isnull', False), ('completed_at__isnull', False), ('failure_reason__isnull', True), ('status', 'SUCCESS')), _connector='OR'), name='valid_status_consistency'), models.UniqueConstraint(fields=('patient',), name='unique_auto_assignment_per_patient')],
            },
        ),
    ]
