# Generated by Django 6.0 on 2026-02-21 13:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emr', '0073_product_purchase_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoAssignmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('status', models.SmallIntegerField(choices=[(1, 'PENDING'), (2, 'SUCCESS'), (3, 'FAILED')], default=1)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='care_quick__status_9c5cd8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status', 1), models.Q(('failure_reason__isnull', False), ('status', 3)), models.Q(('assigned_staff__isnull', False), ('status', 2)), _connector='OR'), name='valid_status_and_reason_or_staff'), models.UniqueConstraint(fields=('patient',), name='unique_auto_assignment_per_patient')],
            },
        ),
    ]
