# Generated by Django 6.0 on 2026-03-13 07:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_quick_assign', '0001_initial'),
        ('facility', '0484_remove_facility_discount_codes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoAssignmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('enabled', models.BooleanField(default=False)),
                ('max_patients_per_staff', models.PositiveIntegerField(blank=True, null=True)),
                ('max_patients_in_total', models.PositiveIntegerField(blank=True, null=True)),
                ('retry_attempts', models.PositiveIntegerField(default=1)),
                ('window_size', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('skill_weight', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('workload_weight', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facility.facility')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('skill_weight__gte', 0), ('skill_weight__lte', 5)), name='skill_weight_range_0_5'), models.CheckConstraint(condition=models.Q(('workload_weight__gte', 0), ('workload_weight__lte', 5)), name='workload_weight_range_0_5')],
            },
        ),
    ]
