# Generated by Django 6.0 on 2026-03-05 10:00

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_quick_assign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoAssignmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('enabled', models.BooleanField(default=False)),
                ('max_patients_per_staff', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('skill_weight', models.PositiveIntegerField(default=1)),
                ('workload_weight', models.PositiveIntegerField(default=1)),
                ('acuity_weight', models.PositiveIntegerField(default=1)),
                ('location_weight', models.PositiveIntegerField(default=1)),
                ('retry_attempts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
