# Generated by Django 6.0 on 2026-03-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_quick_assign', '0002_autoassignmentconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoassignmentconfig',
            name='window_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='autoassignmentconfig',
            name='retry_attempts',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
